spring:
    profiles:
        active: local    servlet:        multipart:            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB
server:
    port: 8081
    error:
        whitelabel:
            enabled: false
        path: /error
        include-exception: true
        include-stacktrace: always
jasypt:
    encryptor:
        bean: jasyptStringEncryptor


--- #local설정
spring:
    config:
        activate:
            on-profile: local # spring boot 2.4.0 부터 변경된 프로파일 정의 설정
    session:
        store-type: jdbc    # spring session 저장타입지정 / spring-session-jdbc를 추가하면 jdbc가 기본으로 동작해서 임시로 동작중지함.de
        timeout: 12h
        jdbc:
            cleanup-cron: 0 0/30 * * * *
    first:
        datasource:  # Postgresql DB APP
            jdbc-url: jdbc:postgresql://110.45.156.163:31707/postgres?currentSchema=ptl
            driver-class-name: org.postgresql.Driver
            type: com.zaxxer.hikari.HikariDataSource
            username: ptl_app
            #password: ptlapp#1
            # Jasypt 로 password 처리
            password: ENC(IRvb+kRnYSNyMpNanCb1XGij/KqGxWANk43MRhDA/csF/NQ3hrv6+5MDQs86puR4)
            hikari:
                minimum-idle: 2
                maximum-pool-size: 10
                connection-timeout: 100000
                connection-test-query: select 1 from dual
    second:
        datasource: # Postgresql DB SESSION
            jdbc-url: jdbc:postgresql://110.45.156.163:31707/postgres?currentSchema=ssn_mgr
            driver-class-name: org.postgresql.Driver
            type: com.zaxxer.hikari.HikariDataSource
            username: ptl_ssn
            #password: ptlssn#1
            # Jasypt 로 password 처리
            password: ENC(KVJM3VmoR736kSLPBGA164V9ktMVzxb5tXVpRzp0/FqIJrGpWCY00PmIZrDKlrrY)
            hikari:
                minimum-idle: 1
                maximum-pool-size: 2
                connection-timeout: 100000
                connection-test-query: select 1 from dual
    quartz:
        auto-startup: true
        overwrite-existing-jobs: true
        properties:
            org:
                quartz:
                    threadPool:
                        threadCount: 10
    devtools:   # 개발툴 이용 관련, 로컬에 개발시에만 사용
        livereload:
            enabled: true
        restart:
            enabled: true
    task:
        execution:
            thread-name-prefix:  task-
            pool:
                core-size: 8
                max-size: 10
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

debug: false
logging:
    level:
        '[root]': info
        '[com.shinvest.ap]': debug
        '[com.shinvest.ap.app.mapper]': info
        '[com.rathontech]': trace
#        '[org.springframework]': trace
    pattern:
        console:  "%clr([%d{yyyy-MM-dd HH:mm:ss.SSS}]){faint} %clr([%5p]) %clr([%15.15t]){faint} %clr([%-40.40logger{39}]){cyan} [%4L] [PORTAL] [ADMIN] %m%n%wEx"

# menuCheck ignore URL
menuCheck:
    ignoreUrls: /, /login, /error/**, /css/**, /js/**, /images/**, /font/**, /webjars/**, /favicon.ico, /test/**

# TABLEAU Properties
tableau-props:
    #api-url: "http://172.17.4.140:8090/api/3.0"
    #token-url: "http://172.17.4.140:8090/trusted/"
    api-url: "https://bitest.shinhaninvest.com/api/3.0"
    token-url: "https://bitest.shinhaninvest.com/trusted/"
    schema-location: "tableauSchema/ts-api_3_0.xsd" # 태블로 api사용을 위한 스키마 파일 정보 위치 버전에 따라서 스키마 파일을 서버에 위치시킴
    username: "admin"
    userpw: "ENC(da5KQDroEogKlXesnczQggJMng/45YFOcB5p5yQXUfrx61xFi7SP6DCTYO52VQhY)"
    default-content-url: ""
    target-site: ""
    cache-preview-path: "c:/works/temp/cache/preview-image"

# HR 파일 경로
hr-props:
  base-path: "c:/works/temp/hr"
  backup-path: "c:/works/temp/backup/hr"
  encoding: "EUC-KR"
  user-file: "EMP.dsv"
  dept-file: "DEPT.dsv"
  hdept-file: "HDEPT.dsv"
  pstn-file: "POSITION.dsv"
  base-dept-cl-path: "c:/works/temp/hr"
  dept-cl-file: "deptinfo.dsv"
  base-photo-path: "c:/works/temp/photo"
  cache-photo-path: "c:/works/temp/cache/user-photo"

#EAI 수집 로그
log-to-file-props:
  log-path: "c:/works/temp/log"
  encoding: "EUC-KR"
  delete-pd: "-7"
  user-file: "T_USER_{DATE}.dsv"
  user-hist-file: "T_USER_HIST_{DATE}.dsv"
  rqst-mgr-sys-file: "T_LOG_RQST_MGR_SYS_{DATE}.dsv"
  rqst-user-sys-file: "T_LOG_RQST_USER_SYS_{DATE}.dsv"
  tableau-mgr-sys-file: "T_LOG_TABLEAU_MGR_SYS_{DATE}.dsv"
  tableau-user-sys-file: "T_LOG_TABLEAU_USER_SYS_{DATE}.dsv"
  bizmeta-mgr-sys-file: "T_LOG_BIZMETA_MGR_SYS_{DATE}.dsv"
  bizmeta-user-sys-file: "T_LOG_BIZMETA_USER_SYS_{DATE}.dsv"
  aws-mgr-sys-file: "T_LOG_AWS_MGR_SYS_{DATE}.dsv"
  aws-user-sys-file: "T_LOG_AWS_USER_SYS_{DATE}.dsv"
  aprv-rqst-file: "T_APRV_RQST_{DATE}.dsv"

#시스템 수집 로그
log-sys-props:
  log-path: "c:/works/temp/log-sys"
  encoding: "EUC-KR"
  delete-pd: "-7"
  user-rqst-cnt-file: "sdap_count_log_{DATE}.dsv"

# UDB Properties
udb-props:
    channel-type: "SU"
    host-name: "cdapapwl02"
    prod-check: "T"

# Eai SOCKET Client and Server
eai-socket:
    host: "172.17.14.135"
    port: "15792"
    notify-port: "15795"
    encoding: "EUC-KR"
    server-port: "15799"
# 골드윙 설정 (goldwing 결재 url 생성시 사용)
goldwing-props:
    #conndoc-url: "http://192.168.12.27/connDoc.aspx"
    conndoc-url: "http://goldwing.shinhan.com/connDoc.aspx"
    svc-code: "GS_SDAP"
    form-id: "2021000004"
    eai-interface-id: "GDWDAPON0001"    
    eai-service-code: "SEAI001Q1"

# AWS Properties
aws-props:
    db-key-first: "DAP-PTL-DEV-DB-1ST"
    db-key-second: "DAP-PTL-DEV-DB-2ND"
    tableau-key: "DAP-PTL-DEV-TABLEAU-KEY"
    bucket-name: "w-shi-an2-dap-dev-s3-att-pt"
    file-path: "board"
    preview-path: "preview-image"
    view-path: "view-image"
    photo-path: "user-photo"
    page-size: "10"
    time-zone: "Asia/Seoul"
    sagemaker-domain-id: "d-thzxgwuqmieq"

# 외부 제공 데이터
news-props:
  encoding: "EUC-KR"
  news-path: "c:/works/temp/news"
  news-file: "news_dw.dsv"
  research-path: "c:/works/temp/research"
  research-file: "research_dw.dsv"
  ranking-path: "c:/works/temp/ranking"
  online-ranking-file: "onlineranking.dsv"
  scatchinterest-ranking-file: "scatchinterestranking.dsv"
  scatchstbd-ranking-file: "scatchstbdranking.dsv"

# 외부 데이터 엑셀업로드
external-data-props:
  excel-path: "c:/works/temp/external-data"




--- #dev
spring:
    config:
        activate:
            on-profile: dev # spring boot 2.4.0 부터 변경된 프로파일 정의 설정
    session:
        store-type: jdbc # spring session 저장타입지정 / spring-session-jdbc를 추가하면 jdbc가 기본으로 동작해서 임시로 동작중지함.
        timeout: 8h
    first:
        datasource:  # Postgresql DB APP
            jdbc-url: jdbc:postgresql://192.168.56.11:5432/postgres?currentSchema=ptl
            driver-class-name: org.postgresql.Driver
            type: com.zaxxer.hikari.HikariDataSource
            username: ptl_app
            password: ENC(IRvb+kRnYSNyMpNanCb1XGij/KqGxWANk43MRhDA/csF/NQ3hrv6+5MDQs86puR4)
            hikari:
                minimum-idle: 10
                maximum-pool-size: 300
                connection-timeout: 100000
                connection-test-query: select 1
    second:
        datasource: # Postgresql DB SESSION
            jdbc-url: jdbc:postgresql://192.168.56.11:5432/postgres?currentSchema=ssn_mgr
            driver-class-name: org.postgresql.Driver
            type: com.zaxxer.hikari.HikariDataSource
            username: ptl_ssn
            password: ENC(KVJM3VmoR736kSLPBGA164V9ktMVzxb5tXVpRzp0/FqIJrGpWCY00PmIZrDKlrrY)
            hikari:
                minimum-idle: 10
                maximum-pool-size: 300
                connection-timeout: 100000
                connection-test-query: select 1
    quartz:
        auto-startup: true
        overwrite-existing-jobs: true
        properties:
            org:
                quartz:
                    threadPool:
                        threadCount: 10
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    task:
        execution:
            thread-name-prefix: task-
            pool:
                core-size: 8
                max-size: 10

debug: false
logging:
    level:
        '[root]': warn
        '[com.shinvest.ap]': debug
        '[com.shinvest.ap.app.mapper]': info
    pattern:
        console: "%clr([%d{yyyy-MM-dd HH:mm:ss.SSS}]){faint} %clr([%5p]) %clr([%15.15t]){faint} %clr([%-40.40logger{39}]){cyan} [%4L] [PORTAL] [ADMIN] %m%n%wEx"

# menuCheck ignore URL
menuCheck:
    ignoreUrls: /, /login, /error, /error/error, /error/notFound, /error/internalServerError, /test

# TABLEAU Properties
tableau-props:
    #api-url: "http://172.17.4.140:8090/api/3.0"
    #token-url: "http://172.17.4.140:8090/trusted/"
    api-url: "https://bitest.shinhaninvest.com/api/3.0"
    token-url: "https://bitest.shinhaninvest.com/trusted/"
    schema-location: "tableauSchema/ts-api_3_0.xsd" # 태블로 api사용을 위한 스키마 파일 정보 위치 버전에 따라서 스키마 파일을 서버에 위치시킴
    username: "admin"
    userpw: "ENC(da5KQDroEogKlXesnczQggJMng/45YFOcB5p5yQXUfrx61xFi7SP6DCTYO52VQhY)"
    default-content-url: ""
    target-site: ""
    cache-preview-path: "/app001/data/cache/preview-image"

# HR 파일 경로
hr-props:
  base-path: "/app001/data/hr"
  backup-path: "/app001/data/backup/hr"
  encoding: "EUC-KR"
  user-file: "EMP.txt"
  dept-file: "DEPT.txt"
  hdept-file: "HDEPT.txt"
  pstn-file: "POSITION.txt"
  base-dept-cl-path: "/app001/data/hr"
  dept-cl-file: "deptinfo.txt"
  base-photo-path: "/app001/data/photo"
  cache-photo-path: "/app001/data/cache/user-photo"

#EAI 수집 로그
log-to-file-props:
  log-path: "/app001/data/log"
  encoding: "EUC-KR"
  delete-pd: "-7"
  user-file: "T_USER_{DATE}.csv"
  user-hist-file: "T_USER_HIST_{DATE}.csv"
  rqst-mgr-sys-file: "T_LOG_RQST_MGR_SYS_{DATE}.csv"
  rqst-user-sys-file: "T_LOG_RQST_USER_SYS_{DATE}.csv"
  tableau-mgr-sys-file: "T_LOG_TABLEAU_MGR_SYS_{DATE}.csv"
  tableau-user-sys-file: "T_LOG_TABLEAU_USER_SYS_{DATE}.csv"
  bizmeta-mgr-sys-file: "T_LOG_BIZMETA_MGR_SYS_{DATE}.csv"
  bizmeta-user-sys-file: "T_LOG_BIZMETA_USER_SYS_{DATE}.csv"
  aws-mgr-sys-file: "T_LOG_AWS_MGR_SYS_{DATE}.csv"
  aws-user-sys-file: "T_LOG_AWS_USER_SYS_{DATE}.csv"
  aprv-rqst-file: "T_APRV_RQST_{DATE}.csv"

#시스템 수집 로그
log-sys-props:
  log-path: "/app001/data/log-sys"
  encoding: "EUC-KR"
  delete-pd: "-7"
  user-rqst-cnt-file: "sdap_count_log_{DATE}.txt"

# UDB Properties
udb-props:
    channel-type: "SU"
    host-name: "cdapapwl02"
    prod-check: "T"

# EAI SOCKET Client and Server
eai-socket:
    host: "172.17.14.135"
    port: "15792"
    notify-port: "15795"
    encoding: "EUC-KR"
    server-port: "15799"
# 골드윙 설정 (goldwing 결재 url 생성시 사용)
goldwing-props:
    #conndoc-url: "http://192.168.12.27/connDoc.aspx"
    conndoc-url: "http://goldwing.shinhan.com/connDoc.aspx"
    svc-code: "GS_SDAP"
    form-id: "2021000004"
    eai-interface-id: "GDWDAPON0001"
    eai-service-code: "SEAI001Q1"    

# AWS Properties
aws-props:
    db-key-first: "DAP-PTL-DEV-DB-1ST"
    db-key-second: "DAP-PTL-DEV-DB-2ND"
    tableau-key: "DAP-PTL-DEV-TABLEAU-KEY"
    bucket-name: "w-shi-an2-dap-dev-s3-att-pt"
    file-path: "board"
    preview-path: "preview-image"
    view-path: "view-image"
    photo-path: "user-photo"
    page-size: "10"
    time-zone: "Asia/Seoul"
    sagemaker-domain-id: "d-thzxgwuqmieq"

# 외부 제공 데이터
news-props:
  encoding: "EUC-KR"
  news-path: "/app001/data/news"
  news-file: "news_dw.txt"
  research-path: "/app001/data/research"
  research-file: "research_dw.txt"
  ranking-path: "/app001/data/ranking"
  online-ranking-file: "onlineranking.txt"
  scatchinterest-ranking-file: "scatchinterestranking.txt"
  scatchstbd-ranking-file: "scatchstbdranking.txt"

# 외부 데이터 엑셀업로드
external-data-props:
  excel-path: "/app001/data/external-data"




--- #prod
spring:
    config:
        activate:
            on-profile: prod
    session:
        store-type: jdbc # spring session 저장타입지정 / spring-session-jdbc를 추가하면 jdbc가 기본으로 동작해서 임시로 동작중지함.
        timeout: 10m
    first:
        datasource:  # Postgresql DB APP
            jdbc-url: jdbc:postgresql://portaldb.dap.r53:15432/dappt?currentSchema=ptl
            driver-class-name: org.postgresql.Driver
            type: com.zaxxer.hikari.HikariDataSource
            username: copr85
            hikari:
                minimum-idle: 10
                maximum-pool-size: 300
                connection-timeout: 100000
                connection-test-query: select 1
    second:
        datasource: # Postgresql DB SESSION
            jdbc-url: jdbc:postgresql://portaldb.dap.r53:15432/dappt?currentSchema=ssn_mgr
            driver-class-name: org.postgresql.Driver
            type: com.zaxxer.hikari.HikariDataSource
            username: copr86
            hikari:
                minimum-idle: 10
                maximum-pool-size: 300
                connection-timeout: 100000
                connection-test-query: select 1
    quartz:
        auto-startup: true
        overwrite-existing-jobs: true
        properties:
            org:
                quartz:
                    threadPool:
                        threadCount: 10
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    task:
        execution:
            thread-name-prefix: task-
            pool:
                core-size: 8
                max-size: 10

debug: false
logging:
    level:
        '[root]': error
        '[com.shinvest.ap]': info
        '[com.shinvest.ap.app.mapper]': error
    pattern:
        console: "%clr([%d{yyyy-MM-dd HH:mm:ss.SSS}]){faint} %clr([%5p]) %clr([%15.15t]){faint} %clr([%-40.40logger{39}]){cyan} [%4L] [PORTAL] [ADMIN] %m%n%wEx"

# menuCheck ignore URL
menuCheck:
    ignoreUrls: /, /login, /error, /error/error, /error/notFound, /error/internalServerError, /test

# TABLEAU Properties
tableau-props:
    api-url: "https://bi.shinhaninvest.com/api/3.0"
    token-url: "https://bi.shinhaninvest.com/trusted/"    
    schema-location: "tableauSchema/ts-api_3_0.xsd" # 태블로 api사용을 위한 스키마 파일 정보 위치 버전에 따라서 스키마 파일을 서버에 위치시킴
    username: "admin"
    userpw: "ENC(da5KQDroEogKlXesnczQggJMng/45YFOcB5p5yQXUfrx61xFi7SP6DCTYO52VQhY)"
    default-content-url: ""
    target-site: ""
    cache-preview-path: "/app001/data/cache/preview-image"

# HR 파일 경로
hr-props:
  base-path: "/app001/data/hr"
  backup-path: "/app001/data/backup/hr"
  encoding: "EUC-KR"
  user-file: "EMP.txt"
  dept-file: "DEPT.txt"
  hdept-file: "HDEPT.txt"
  pstn-file: "POSITION.txt"
  base-dept-cl-path: "/app001/data/hr"
  dept-cl-file: "deptinfo.txt"
  base-photo-path: "/app001/data/photo"
  cache-photo-path: "/app001/data/cache/user-photo"

#EAI 수집 로그
log-to-file-props:
  log-path: "/app001/data/log"
  encoding: "EUC-KR"
  delete-pd: "-7"
  user-file: "T_USER_{DATE}.csv"
  user-hist-file: "T_USER_HIST_{DATE}.csv"
  rqst-mgr-sys-file: "T_LOG_RQST_MGR_SYS_{DATE}.csv"
  rqst-user-sys-file: "T_LOG_RQST_USER_SYS_{DATE}.csv"
  tableau-mgr-sys-file: "T_LOG_TABLEAU_MGR_SYS_{DATE}.csv"
  tableau-user-sys-file: "T_LOG_TABLEAU_USER_SYS_{DATE}.csv"
  bizmeta-mgr-sys-file: "T_LOG_BIZMETA_MGR_SYS_{DATE}.csv"
  bizmeta-user-sys-file: "T_LOG_BIZMETA_USER_SYS_{DATE}.csv"
  aws-mgr-sys-file: "T_LOG_AWS_MGR_SYS_{DATE}.csv"
  aws-user-sys-file: "T_LOG_AWS_USER_SYS_{DATE}.csv"
  aprv-rqst-file: "T_APRV_RQST_{DATE}.csv"

#시스템 수집 로그
log-sys-props:
  log-path: "/app001/data/log-sys"
  encoding: "EUC-KR"
  delete-pd: "-7"
  user-rqst-cnt-file: "sdap_count_log_{DATE}.txt"

# UDB Properties
udb-props:
    channel-type: "SU"
    host-name: "pdapapwl03"
    prod-check: "P"

# EAI SOCKET Client and Server
eai-socket:
    host: "172.17.11.105"
    port: "15792"
    notify-port: "15795"
    encoding: "EUC-KR"
    server-port: "15799"
# 골드윙 설정 (goldwing 결재 url 생성시 사용)
goldwing-props:
    conndoc-url: "http://goldwing.shinhan.com/connDoc.aspx"
    svc-code: "GS_SDAP"
    form-id: "2021000002"
    eai-interface-id: "GDWDAPON0001"
    eai-service-code: "SEAI001Q1"

# AWS Properties
aws-props:
    db-key-first: "DAP-PTL-PRD-DB-1ST"
    db-key-second: "DAP-PTL-PRD-DB-2ND"
    tableau-key: "DAP-PTL-PRD-TABLEAU-KEY"
    bucket-name: "w-shi-an2-dap-prd-s3-att-pt"
    file-path: "board"
    preview-path: "preview-image"
    view-path: "view-image"
    photo-path: "user-photo"
    page-size: "10"
    time-zone: "Asia/Seoul"
    sagemaker-domain-id: "d-thzxgwuqmieq"

# 외부 제공 데이터
news-props:
  encoding: "EUC-KR"
  news-path: "/app001/data/news"
  news-file: "news_dw.txt"
  research-path: "/app001/data/research"
  research-file: "research_dw.txt"
  ranking-path: "/app001/data/ranking"
  online-ranking-file: "onlineranking.txt"
  scatchinterest-ranking-file: "scatchinterestranking.txt"
  scatchstbd-ranking-file: "scatchstbdranking.txt"

# 외부 데이터 엑셀업로드
external-data-props:
  excel-path: "/app001/data/external-data"
